### ISSUE TITLE
Long running instance has old title

### ISSUE THREAD

**Issue by SSaishruthi** [IBM/MAX-Audio-Classifier#32]
Current title for long-running instance: Model Asset Exchange Microservice
To be changed: MAX Audio Classifier

**Comment by ajbozarth** [comment]
Looking at the changes since the last release this has been fixed but not released. So this can be solved by cutting a new release and updating the long running instance's version. Instructions for a release are here: https://github.ibm.com/CODAIT/MAX-development-guide/blob/master/VERSIONING.md and instructions for updating the instance are here: https://github.ibm.com/CODAIT/MAX-development-guide/blob/master/IBM_CLOUD_GUIDE.md
